parserOptions:
  ecmaVersion: 9

plugins:
  - prettier

rules:
  prettier/prettier:
    - error
    - parser: x-babel
      arrowParens: avoid
      endOfLine: auto
      semi: false
      singleQuote: true
      spaceBeforeFunctionParen: true
      trailingComma: none
