parserOptions:
  ecmaVersion: 9

extends: standard

plugins:
  - prettier
  - jest

env: { jest/globals: true }

rules:
  prettier/prettier:
    - error
    - parser: x-babel
      arrowParens: avoid
      endOfLine: auto # needed for CI on Windows
      semi: false
      singleQuote: true
      spaceBeforeFunctionParen: true
      trailingComma: none
  # TODO resolve these ignored "Standard JS" rules:
  quotes: 0
  curly: 0
  no-undef: 0
