parserOptions:
  ecmaVersion: 9

plugins:
  - prettier

rules:
  prettier/prettier:
    - error
    - parser: prettierx-babel
      endOfLine: auto
      semi: false
      singleQuote: true
      spaceBeforeFunctionParen: true
