parserOptions:
  ecmaVersion: 9

extends:
  - standard
  - plugin:prettier/recommended

plugins:
  - prettier
  - jest

env: { jest/globals: true }

rules:
  prettier/prettier:
    - error
    - parser: x-babel
      arrowParens: avoid
      endOfLine: auto # needed for CI on Windows
      semi: false
      singleQuote: true
      spaceBeforeFunctionParen: true
      trailingComma: none
  # TODO resolve ignored "Standard JS" rule:
  curly: 0
